### ISSUE TITLE
EQUIFAX No More Narratives (September, 2019-onwards)

### ISSUE THREAD

**Issue by nuno-chicoria** [cfpb/api#71]
Since middle of September EQUIFAX, INC. stopped having complaints with narratives. Is this an API problem?

**Comment by sephcoster** [comment]
Thank you for your comment. 

Publishing narratives can take over 60 days, depending on where a complaint is in the process or the time needed to scrub personally identifiable information to protect consumer privacy. Also, we only publish narratives consumers have opted to share.
